final Map<String, String> fieldLabels = {
  "tanggal": "Tanggal",
  "nama": "Nama",
  "jenis_kelamin": "Jenis Kelamin",
  "usia": "Usia",
  "berat_badan_terhadap_umur": "Berat Badan Terhadap Umur",
  "tinggi_badan_terhadap_umur": "Tinggi Badan Terhadap Umur",
  "berat_badan_terhadap_tinggi": "Berat Badan Terhadap Tinggi",
  "lingkar_kepala_terhadap_umur": "Lingkar Kepala Terhadap Umur",
  "lingkar_lengan_atas": "Lingkar Lengan Atas",
  "posisi_anak": "Posisi Anak",
  "ibu_hamil": "Ibu Hamil",
  "pendidikan_ibu": "Pendidikan Ibu",
  "kondisi_ekonomi": "Kondisi Ekonomi",
  "pemeriksaan_rutin": "Pemeriksaan Rutin",
  "istirahat": "Istirahat",
  "menghindari_rokok": "Menghindari Rokok",
  "riwayat_penyakit": "Riwayat Penyakit",
  "kesehatan_mental": "Kesehatan Mental",
  "persalinan": "Persalinan",
  "layanan_kesehatan": "Layanan Kesehatan",
  "asi": "ASI",
  "pendamping_asi": "Pendamping ASI",
  "kualitas_mpasi": "Kualitas MPASI",
  "makan_anak": "Makan Anak",
  "pola_makan": "Pola Makan",
  "status_gizi": "Status Gizi",
  "riwayat_imunisasi": "Riwayat Imunisasi",
  "kebersihan_lingkungan": "Kebersihan Lingkungan",
  "kebersihan_diri": "Kebersihan Diri",
  "olahraga": "Olahraga",
  "dukungan_keluarga": "Dukungan Keluarga",
  "pola_asuh": "Pola Asuh",

  // hasil prediksi / rekomendasi
  "indikasi_awal":
      "Indikasi Awal (Dasar Klinis Berdasarkan Tinggi Badan Terhadap Umur)",
  "probabilitas_stunting": "Prediksi Stunting",
  "probabilitas_normal": "Prediksi Normal",
  "indikasi": "Penyebab",
  "rekomendasi": "Saran",
};
